name: Extract Info

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  extract_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install packages
      run: pip install beautifulsoup4

    - name: Write sitemap to Repo
      run: python .github/scripts/sitemap.py > sitemap.xml

    - name: Write info files to Repo
      run: python .github/scripts/extract_info.py > info.json

    - name: Check for changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml info.json
        git diff-index --quiet HEAD || git commit -m "Info updated with GitHub Action"
        if [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]; then
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
