name: RSSify Any

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: RSSify Any
      uses: tabhub/rssify@v2
      with:
        title: GitData arXiv
        url: https://arxiv.gd.edu.kg/
        item-title-css: '.article-content .title h1'
        item-description-css: 'head meta[name="citation_abstract"]'
        item-date-css: '.side-block_section span.head:contains("Submission Date") + p'
        item-date-format: 'YYYY/MM/DD'
        item-timezone: 'UTC'
        
